Repository FE-3-2team/team2taskify, pull requests merged in 2025-04, with the labels that each got.

#129 [Feat] 할일 수정, 할일 생성 카드 작업
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/AssigneeCard.tsx
  src/components/ChangePasswordForm.tsx
  src/components/Comments.tsx
  src/components/EditDashboard.tsx
  src/components/EditProfile.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SingupForm.tsx
  src/components/ModalContents/EditCard.modal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/ModalContents/NewCard.modal.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Card/CardValues.tsx
  src/components/common/Card/card.form.tsx
  src/components/common/Comment.card.tsx
  src/components/common/Dropdown/250331_DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownProgress.tsx
  src/components/common/ImageUploadBox.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/tagInput.tsx
  src/hooks/useEditCard.tsx
  src/hooks/useFormatDate.tsx
  src/pages/mydashboard.tsx
  src/pages/test.tsx
  src/types/global.d.ts
Labels: Feat, Refactor

#131 [Feat] 드래그앤드롭 후 카드수정
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/AssigneeCard.tsx
  src/components/ChangePasswordForm.tsx
  src/components/Comments.tsx
  src/components/EditDashboard.tsx
  src/components/EditProfile.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SingupForm.tsx
  src/components/ModalContents/CreateCardModal.tsx
  src/components/ModalContents/EditCard.modal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/ModalContents/NewCard.modal.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Card/CardValues.tsx
  src/components/common/Card/card.form.tsx
  src/components/common/Comment.card.tsx
  src/components/common/Dropdown/250331_DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownProgress.tsx
  src/components/common/ImageUploadBox.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/tagInput.tsx
  src/components/common/ModalPopup.tsx
  src/components/common/SortableCard.tsx
  src/components/common/SortableColumn.tsx
  src/components/common/TodoCard.tsx
  src/hooks/useCardForm.tsx
  src/hooks/useDashboardStates.ts
  src/hooks/useEditCard.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFormatDate.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/test.tsx
  src/types/global.d.ts
Labels: Feat

#132 [Refactor] 대시보드 상세페이지 모달 오픈
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/CreateCard.modal.tsx
  src/components/ModalContents/CreateCardModal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/ModalContents/ManageColumnModal.tsx
  src/components/common/Card/CardValues.tsx
  src/components/common/Card/card.form.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/components/common/Column.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/tagInput.tsx
  src/components/common/ModalPopup.tsx
  src/components/common/SortableCard.tsx
  src/components/common/SortableColumn.tsx
  src/components/common/TagInputField.tsx
  src/components/common/TodoCard.tsx
  src/components/forms/CardForm.tsx
  src/hooks/useCardForm.tsx
  src/hooks/useCreateCard.tsx
  src/hooks/useDashboardStates.ts
  src/hooks/useEditCard.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFetchColumns.tsx
  src/hooks/useFormatDate.tsx
  src/hooks/useHandleEditCardClick.tsx
  src/hooks/useValidation.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
  src/types/column.ts
  src/types/global.d.ts
Labels: Refactor

#133 [Refactor] 수정시 assignee , 컬럼 변경 오류 수정
  src/api/card.api.ts
  src/components/ModalContents/CreateCard.modal.tsx
  src/components/ModalContents/EditCard.modal.tsx
  src/components/common/Card/CardValues.tsx
  src/components/common/Column.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownProgress.tsx
  src/components/common/ImageUploadBox.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style, Refactor

#134 [fix] 카드 수정후 화면에 반영 ,카드 수정 모달 오류 수정
  src/api/card.api.ts
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/EditCard.modal.tsx
  src/components/common/Card/CardValues.tsx
  src/components/common/Chip/Status.chip.tsx
  src/components/common/Column.tsx
  src/components/common/ModalPopup.tsx
  src/components/common/SortableCard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Fix, Refactor

#135 [Style] [dashboardId] 페이지에서 스타일 오류 수정
  src/components/common/ModalPopup.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Style
