Repository FE-3-2team/team2taskify, pull requests merged in 2025-03, with the labels that each got.

#1 [Chore]Update issue templates
  .github/ISSUE_TEMPLATE/todo-이슈-생성시-사용해-주세요.md
Labels: Chore

#4 [Chore] npm install tailwindcss@4
  next.config.ts
  package-lock.json
  package.json
  postcss.config.js
  src/styles/Home.module.css
  src/styles/globals.css
  tailwind.config.js
  tsconfig.json
Labels: Chore

#10 [Feat] create chip & random tags
  src/assets/icons/ColorChip.icons.svg
  src/assets/icons/Plus.icon.svg
  src/components/common/Chip/CardCount.chip.tsx
  src/components/common/Chip/Color.chip.tsx
  src/components/common/Chip/Plus.chip.tsx
  src/components/common/Chip/Status.chip.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/pages/test.tsx
  src/styles/globals.css
  tailwind.config.js
Labels: Feat

#11 [Feat] create Badge, profile
  package-lock.json
  package.json
  src/components/common/Badge.tsx
  src/components/common/Profile.tsx
  src/hooks/useWindow.tsx
  src/types/global.d.ts
Labels: Feat, Style

#19 [Feat] #5 Assignee card
  src/components/AssigneeCard.tsx
Labels: Feat

#20 [Feat] create Header
  src/assets/icons/Crown.icon.svg
  src/assets/icons/Edit.icon.svg
  src/assets/icons/Invite.icon.svg
  src/components/common/Badge.tsx
  src/components/common/Chip/CardCount.chip.tsx
  src/components/common/Chip/Color.chip.tsx
  src/components/common/Chip/Plus.chip.tsx
  src/components/common/Chip/Status.chip.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/pages/test.tsx
  src/styles/color.css
  src/types/global.d.ts
Labels: Feat

#22 [Feat] create newDashboard modal dashboard modal
  src/api/dashboard.ts
  src/api/instance.ts
  src/assets/icons/X.icon.svg
  src/components/AssigneeCard.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Chip/Color.chip.tsx
  src/components/common/Comments.tsx
  src/components/common/Header.tsx
  src/pages/test.tsx
  src/types/global.d.ts
Labels: Feat

#23 [Feat] create InvitationHistory.tsx and edit member.tsx
  src/api/dashboard.ts
  src/api/member.ts
  src/assets/icons/NextPage.icon.svg
  src/assets/icons/PrevPage.icon.svg
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Badge.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/pages/test.tsx
  src/styles/globals.css
  src/types/global.d.ts
Labels: Feat

#35 [Feat] Add responsive styles to AssigneeCard
  src/components/AssigneeCard.tsx
Labels: Feat

#38 [Refactor] 코드리뷰 수정 & 오타 수정 & 컬러 변수 변경
  src/api/dashboard.ts
  src/api/instance.ts
  src/api/login.ts
  src/api/member.ts
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Badge.tsx
  src/components/common/Chip/CardCount.chip.tsx
  src/components/common/Chip/Color.chip.tsx
  src/components/common/Chip/Plus.chip.tsx
  src/components/common/Chip/Status.chip.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/hooks/useWindow.tsx
  src/pages/test.tsx
  src/styles/globals.css
  src/utils/localstorage.ts
Labels: Chore, Refactor

#39 [Refacor]Comment
  package-lock.json
  package.json
  src/components/common/Badge.tsx
  src/components/common/Comments.tsx
  src/pages/test.tsx
  src/types/global.d.ts
Labels: Feat, Refactor

#42 [Feat] Add TodoCard and Column components
  src/components/common/Column.tsx
  src/components/common/TodoCard.tsx
Labels: Feat

#45 [Refactor] edit comments & profile & header & setting zustand
  package-lock.json
  package.json
  src/api/auth.ts
  src/api/comment.ts
  src/api/instance.ts
  src/api/login.ts
  src/components/EditMember.tsx
  src/components/common/Badge.tsx
  src/components/common/Comments.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/hooks/useFormatDate.tsx
  src/hooks/useWindow.tsx
  src/pages/dashboard/[dashboard]/edit.tsx
  src/pages/dashboard/[dashboard]/index.tsx
  src/pages/mydashboard.tsx
  src/pages/mypage.tsx
  src/pages/test.tsx
  src/types/global.d.ts
  src/utils/Zustand/useStore.ts
  src/utils/Zustand/zustand.ts
Labels: Refactor

#48 [Feat] create Card modal & edit assigneeCard
  src/api/card.api.ts
  src/components/AssigneeCard.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/common/Badge.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/components/common/Comments.tsx
  src/components/common/Dropdown/DropdownEditDel.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/styles/globals.css
  src/types/global.d.ts
Labels: Feat

#50 [Feat] create edit page with getstaticProps
  src/api/dashboard.ts
  src/api/invitations.api.ts
  src/api/member.ts
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Button/DashButton.tsx
  src/components/common/Chip/Color.chip.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/dashboard/[dashboard]/edit.tsx
Labels: Feat

#51 [Feat] Input 수정, validation hook 추가
  src/components/common/Input.tsx
  src/hooks/useDebounce.tsx
  src/hooks/useValidation.tsx
Labels: Feat

#52 [Fix] Correct duplicate styles in TodoCard by applying media query
  src/components/common/TodoCard.tsx
Labels: Fix

#54 [Feat] ReusableModal (미완)
  src/components/ModalContents/ColumnModal.tsx
  src/components/ModalContents/GenericModal.tsx
  src/components/ModalContents/ReusableModal.tsx
  src/pages/SJmodaltest.tsx
Labels: Feat

#55 [fix] header 프로필 오류 수정
  src/assets/icons/NextPage.icon.svg
  src/assets/icons/PrevPage.icon.svg
  src/assets/icons/white.Invite.icons.svg
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/styles/globals.css
Labels: Refactor

#56 [Feat] create modal
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/ReusableModal.tsx
  src/components/common/Input.tsx
  src/components/common/ModalPopup.tsx
  src/hooks/useAutoClose.tsx
  src/pages/test.tsx
Labels: Feat

#57 [Feat] Edit dashboard
  src/api/dashboard.ts
  src/components/ModalContents/EditDashboard.tsx
  src/components/common/Chip/Color.chip.tsx
Labels: Feat

#60 [Feat] Login,SignUp,API,Hooks 임시, React-Toastify 추가
  package-lock.json
  package.json
  src/api/auth.ts
  src/assets/MainLogo.png
  src/assets/icons/MainLogo.svg
  src/components/common/Input.tsx
  src/components/common/Login/AuthContainer.tsx
  src/components/common/Login/AuthFormLayout.tsx
  src/components/common/Login/LoginForm.tsx
  src/components/common/Login/SingupForm.tsx
  src/components/common/SjAuthTest.tsx
  src/hooks/useLogin.tsx
  src/hooks/useSign.tsx
  src/hooks/useValidation.tsx
  src/pages/_app.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Feat

#63 [Feat] create inputModal
  src/api/column.api.ts
  src/components/ModalContents/InputModal.tsx
  src/components/common/ModalPopup.tsx
  src/types/global.d.ts
Labels: Feat

#65 [Feat] Invited dashboard
  src/api/invitations.ts
  src/assets/icons/Magnifier.icon.svg
  src/assets/icons/NoInvitation.icon.svg
  src/components/common/Column.tsx
  src/components/common/InvitedDashboards/InvitedDashboards.tsx
  src/components/common/InvitedDashboards/Item.InvDash.tsx
  src/components/common/InvitedDashboards/List.InvDash.tsx
  src/components/common/InvitedDashboards/Search.InvDash.tsx
  src/components/common/TodoCard.tsx
Labels: Feat

#66 [feat] editpage의 InvitationHistory 컴포넌트 핸들러, 페이지 네이션
  src/api/dashboard.ts
  src/api/invitations.api.ts
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/EditDashboard.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/common/Header.tsx
  src/components/common/ModalPopup.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
Labels: Feat

#67 [Feat] Mydashboard page
  src/api/dashboard.ts
  src/components/ModalContents/NewDashboard.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Chip/Color.chip.tsx
  src/components/common/Header.tsx
  src/components/common/InvitedDashboards/InvitedDashboards.tsx
  src/components/common/InvitedDashboards/Search.InvDash.tsx
  src/components/common/ModalPopup.tsx
  src/pages/mydashboard.tsx
Labels: Feat

#68 [Feat]Editpage 의 EditMember 페이지 네이션, 삭제 핸들링
  src/api/member.ts
  src/components/EditMember.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
Labels: Feat

#70 [Feat] Apply infinite scroll to InvitedDashboard
  src/components/InvitedDashboards/InvitedDashboards.tsx
  src/components/InvitedDashboards/Item.InvDash.tsx
  src/components/InvitedDashboards/List.InvDash.tsx
  src/components/InvitedDashboards/Search.InvDash.tsx
Labels: Feat

#71 [build] config 수정
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.js
  src/components/EditDashboard.tsx
  src/components/common/TodoCard.tsx
  tsconfig.json
Labels: Build

#80 [Feat] Column on dashboard index
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/InvitedDashboards/InvitedDashboards.tsx
  src/components/InvitedDashboards/Item.InvDash.tsx
  src/components/InvitedDashboards/List.InvDash.tsx
  src/components/common/Column.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
Labels: Feat

#81 [Feat] create Comment create,get,edit,delete request
  src/api/card.api.ts
  src/api/comment.api.ts
  src/api/comment.ts
  src/components/AssigneeCard.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/common/Comments.tsx
  src/components/common/Input.tsx
  src/components/common/ModalPopup.tsx
Labels: Feat

#82 [Feat] 로그인,회원가입 리팩토링 예정
  src/api/auth.ts
  src/components/Login/AuthContainer.tsx
  src/components/Login/AuthFormLayout.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SingupForm.tsx
  src/components/ModalContents/AlertModal.tsx
  src/components/common/Input.tsx
  src/hooks/useLogin.tsx
  src/hooks/useSignup.tsx
  src/hooks/useValidation.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Feat

#83 [Refactor] auth 수정, console.log delete
  src/api/auth.ts
  src/api/invitations.ts
  src/hooks/useLogin.tsx
  src/pages/inputTest.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
Labels: Refactor

#87 [Refactor] 로그인, 회원가입 로직 수정
  src/api/auth.ts
  src/api/member.ts
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/AlertModal.tsx
  src/components/common/Badge.tsx
  src/components/common/Header.tsx
  src/components/common/SideMenu.tsx
  src/hooks/useSignup.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/login.tsx
  src/pages/mydashboard.tsx
Labels: Refactor

#89 [Feat] Apply functions of new column and new todo card (incomplete)
  src/api/card.api.ts
  src/api/column.api.ts
  src/api/dashboard.ts
  src/components/common/Column.tsx
  src/components/common/ModalPopup.tsx
  src/components/common/TagInputField.tsx
  src/components/common/TodoCard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/index.tsx
Labels: Feat

#91 [Feat] Complete new card modal and fix errors
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/common/Column.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/ImageUploadBox.tsx
  src/components/common/TagInputField.tsx
  src/hooks/useCreateCard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/utils/date.ts
Labels: Feat, Fix, Refactor

#92 [Feat] 계정 관리 페이지 프로필 수정 컴포넌트
  src/assets/icons/CardProfile.svg
  src/components/EditCard.tsx
  src/components/common/Input.tsx
  src/pages/test.tsx
Labels: Feat

#96 [Feat] Default card image, column loading
  src/assets/defaultCardImage.jpg
  src/components/common/Column.tsx
  src/hooks/useCreateCard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/utils/imageToFile.ts
Labels: Feat

#97 [Refactor]
  src/api/auth.ts
  src/api/card.api.ts
  src/api/column.api.ts
  src/api/comment.api.ts
  src/api/dashboard.ts
  src/api/instance.ts
  src/components/Comments.tsx
  src/components/EditDashboard.tsx
  src/components/EditMember.tsx
  src/components/InvitationHistory.tsx
  src/components/InvitedDashboards/InvitedDashboards.tsx
  src/components/InvitedDashboards/Item.InvDash.tsx
  src/components/InvitedDashboards/List.InvDash.tsx
  src/components/InvitedDashboards/Search.InvDash.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/common/Badge.tsx
  src/components/common/Chip/Tag.chip.tsx
  src/components/common/Comment.card.tsx
  src/components/common/Dropdown/LogoutDropdown.tsx
  src/components/common/Header.tsx
  src/components/common/Profile.tsx
  src/components/common/TodoCard.tsx
  src/hooks/useLogin.tsx
  src/hooks/useWindow.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/index.tsx
  src/pages/mydashboard.tsx
  src/utils/AuthContext.tsx
Labels: Style, Refactor

#98 [Feat] 이메일 받아오기
  src/assets/icons/CardProfile.svg
  src/components/EditProfile.tsx
  src/components/common/Input.tsx
Labels: Feat

#101 [Style] 로그인,회원가입 페이지 디자인 수정
  src/assets/icons/CheckBox.svg
  src/assets/icons/UnCheckBox.svg
  src/components/EditProfile.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SingupForm.tsx
  src/components/common/Input.tsx
  src/pages/login.tsx
  src/pages/signup.tsx
Labels: Feat, Style

#103 [Refactor] Skeleton, handling default card image
  src/assets/defaultCardImage.jpg
  src/components/common/Skeleton.tsx
  src/components/common/TagInputField.tsx
  src/components/common/TodoCard.tsx
  src/hooks/useCardImageVisibility.ts
  src/hooks/useCreateCard.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/utils/createInvisibleImageFile.ts
Labels: Feat, Refactor

#105 [Style] 카드 상세보기 모달 반응형
  src/components/AssigneeCard.tsx
  src/components/Comments.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/common/ModalPopup.tsx
  src/pages/mydashboard.tsx
Labels: Style

#107 [Feat] 이미지 업로드 클라이언트 크롭 구현
  package-lock.json
  package.json
  src/components/EditProfile.tsx
  src/pages/test.tsx
Labels: Feat, Style

#109 [Fix] * 숨김처리, 이메일 인풋 스타일 수정
  src/components/EditProfile.tsx
  src/components/common/Input.tsx
Labels: Fix, Style

#115 [Feat] 프로필 수정 컴포넌트 수정
  next.config.ts
  src/assets/MainLogo.png
  src/components/EditProfile.tsx
Labels: Feat

#116 [Feat] Add card edit modal and refactor dashboard/index
  src/api/card.api.ts
  src/api/column.api.ts
  src/components/ModalContents/AddColumnModal.tsx
  src/components/ModalContents/CreateCardModal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/ModalContents/ManageColumnModal.tsx
  src/components/common/Column.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/Dropdown/DropdownEditDel.tsx
  src/components/common/ImageUploadBox.tsx
  src/components/common/ModalPopup.tsx
  src/components/common/TodoCard.tsx
  src/components/forms/CardForm.tsx
  src/hooks/useCardForm.tsx
  src/hooks/useColumnForm.tsx
  src/hooks/useCreateCard.tsx
  src/hooks/useDashboardStates.ts
  src/hooks/useEditCard.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFetchColumns.tsx
  src/hooks/useHandleEditCardClick.tsx
  src/hooks/useInitializeDashboard.ts
  src/pages/dashboard/[dashboardId]/index.tsx
  src/types/column.ts
Labels: Feat, Chore, Refactor

#117 [Feat] 프로필 컨테이너 수정
  src/components/EditProfile.tsx
  src/components/Login/LoginForm.tsx
  src/components/Login/SingupForm.tsx
Labels: Feat

#118 [Style] header 프로필 수정, 계정관리 페이지로 이동
  src/components/common/Badge.tsx
  src/components/common/Dropdown/DropdownEditDel.tsx
  src/components/common/Dropdown/LogoutDropdown.tsx
  src/components/common/Dropdown/Profile.D.D.tsx
  src/components/common/Header.tsx
Labels: Style

#120 [Refactor] 상세 카드 안에 수정하기 모달
  src/components/AssigneeCard.tsx
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/common/Column.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/ModalPopup.tsx
  src/components/forms/CardForm.tsx
  src/hooks/useCardForm.tsx
  src/hooks/useCreateCard.tsx
  src/hooks/useDashboardStates.ts
  src/hooks/useEditCard.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFormatDate.tsx
  src/hooks/useHandleEditCardClick.tsx
  src/hooks/useInitializeDashboard.ts
  src/pages/mydashboard.tsx
  src/types/global.d.ts
Labels: Refactor

#121 [Refactoring] 에러 모달 팝업, header 수정
  src/api/column.api.ts
  src/api/dashboard.ts
  src/api/member.ts
  src/components/EditDashboard.tsx
  src/components/EditMember.tsx
  src/components/EditProfile.tsx
  src/components/InvitationHistory.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/common/Header.tsx
  src/components/common/ModalPopup.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFetchColumns.tsx
  src/hooks/useFormatDate.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/mydashboard.tsx
  src/types/global.d.ts
Labels: Fix, Refactor

#122 [Refactor] header 수정 , styleGuide 페이지 삭제 , 헤더-할일수정-할일상세보기 에러 핸들링
  src/api/card.api.ts
  src/api/column.api.ts
  src/api/dashboard.ts
  src/api/member.ts
  src/components/ModalContents/Card.modal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/common/Badge.tsx
  src/components/common/Header.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/styleguide.tsx
  src/types/global.d.ts
  src/utils/Zustand/zustand.ts
Labels: Chore, Refactor

#123 [Feat] Drag and Drop
  package-lock.json
  package.json
  src/api/card.api.ts
  src/api/column.api.ts
  src/api/dashboard.ts
  src/components/EditDashboard.tsx
  src/components/ModalContents/AddColumnModal.tsx
  src/components/ModalContents/CreateCardModal.tsx
  src/components/ModalContents/EditCardModal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/common/Column.tsx
  src/components/common/DropIndicator.tsx
  src/components/common/Dropdown/DropdownAssigneeSearch.tsx
  src/components/common/SortableCard.tsx
  src/components/common/SortableColumn.tsx
  src/components/common/TodoCard.tsx
  src/hooks/useEditCardSubmit.tsx
  src/hooks/useFetchColumns.tsx
  src/hooks/useInitializeDashboard.ts
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: Feat

#125 [Refactor] 새로운 컬럼 생성 중복검사, 생성 테스트
  src/api/auth.ts
  src/components/ModalContents/AddColumnModal.tsx
  src/components/ModalContents/InputModal.tsx
  src/components/common/Input.tsx
  src/components/common/ModalPopup.tsx
  src/hooks/useValidation.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/mydashboard.tsx
Labels: Refactor

#126 [Fix] 모달 타임아웃처리, 기본 이미지 저장 오류 처리
  src/components/EditProfile.tsx
  src/components/Login/SingupForm.tsx
  src/components/ModalContents/AlertModal.tsx
Labels: Fix
